[package]
name = "protobuf-gen"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = "4.2.2"
prost-build = "0.8"
serde = "1"
serde_derive = "1"
toml = "0.5"
